
name: MCE Dispositions | Miami University

description: The Miami Notebook Program at Miami University

baseurl: /mce

markdown: rdiscount

faculty: ["bob","billy","test"]

permalink: pretty

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
